### PR TITLE
Add ignore.txt files for 2.11 and 2.12

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Please, after merge, add 2.11 to the test matrix (I didn't find it)

https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

### CODE REVIEW

**Comment by justjais** [comment]
@Andersson007 this is an archived repo, checkpoint team is managing the content at: https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection

**Comment by Andersson007** [comment]
@justjais ok thanks for the info. Could anyone push "Archive this repository" in Settings and update the README file respectively ? If nobody has time, I could

**Comment by justjais** [comment]
@Andersson007 yea, so the archive details PR just got merged.

**Comment by Andersson007** [comment]
@justjais thanks!

**Pull request closed without merging**
